package com.visualjava.web

import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.command.WriteCommandAction
import com.intellij.openapi.ui.Messages
import com.intellij.openapi.vfs.LocalFileSystem
import com.intellij.openapi.vfs.VfsUtil
import com.intellij.psi.PsiManager
import com.intellij.psi.xml.XmlFile
import com.visualjava.actions.FxmlEditorAction
import com.visualjava.editor.FxmlPreviewFileEditor
import java.io.File

/**
 * v2 SCAFFOLD action: take the active FXML and emit a Thymeleaf-flavoured HTML
 * template plus a stub Spring controller next to it. Pops a confirmation
 * dialog with the output paths so the user knows what they got.
 *
 * Output:
 *  - <pkg>/web/<FormName>.html       — Thymeleaf template
 *  - <pkg>/web/<FormName>Controller.java  — Spring @Controller stub (commented)
 */
class ExportToWebAction : FxmlEditorAction("Visual Java — Export to Web (Thymeleaf, v2 preview)…") {
    override fun invoke(editor: FxmlPreviewFileEditor) {
        val project = editor.project
        val file = editor.getFile()
        val xmlFile = PsiManager.getInstance(project).findFile(file) as? XmlFile ?: return
        val html = FxmlToHtmlTranslator.translate(xmlFile)
        val name = file.nameWithoutExtension
        val parentIo = File(file.path).parentFile
        val webDir = File(parentIo, "web").also { it.mkdirs() }
        val htmlFile = File(webDir, "$name.html")
        val controllerFile = File(webDir, "${name}Controller.java")

        ApplicationManager.getApplication().runWriteAction {
            htmlFile.writeText(html)
            controllerFile.writeText(controllerStub(name))
            val htmlVf = LocalFileSystem.getInstance().refreshAndFindFileByIoFile(htmlFile)
            val javaVf = LocalFileSystem.getInstance().refreshAndFindFileByIoFile(controllerFile)
            if (htmlVf != null) VfsUtil.markDirtyAndRefresh(true, false, false, htmlVf)
            if (javaVf != null) VfsUtil.markDirtyAndRefresh(true, false, false, javaVf)
        }
        Messages.showInfoMessage(
            project,
            "Wrote (v2 preview):\n  ${htmlFile.absolutePath}\n  ${controllerFile.absolutePath}\n\n" +
                "This is a scaffold — wiring up the Spring app, mapping the binding, and re-rendering\n" +
                "in a browser preview pane are the remaining v2 work.",
            "Export to Web",
        )
    }

    private fun controllerStub(formName: String): String = """
// v2 SCAFFOLD — generated by Visual Java's "Export to Web" action.
// This stub assumes you have spring-boot-starter-web + spring-boot-starter-thymeleaf
// on the classpath. Wire the form's bindings (TextField names → model attributes)
// in `model.addAttribute(...)` calls below.
package web;

// TODO: import org.springframework.stereotype.Controller;
// TODO: import org.springframework.ui.Model;
// TODO: import org.springframework.web.bind.annotation.*;

public class ${formName}Controller {
    // @GetMapping("/${formName.lowercase()}")
    // public String show(Model model) {
    //     // TODO: populate model attributes for every fx:id-bearing input.
    //     return "${formName}";  // resolves to ${formName}.html under templates/
    // }

    // @PostMapping("/${formName.lowercase()}")
    // public String submit(@ModelAttribute SubmitForm form) {
    //     // TODO: handle the submitted values.
    //     return "redirect:/${formName.lowercase()}";
    // }
}
""".trimIndent()
}
