package com.visualjava.palette

import com.visualjava.palette.ComponentDescriptor.Category.COLLECTIONS
import com.visualjava.palette.ComponentDescriptor.Category.CONTAINERS
import com.visualjava.palette.ComponentDescriptor.Category.CONTROLS
import com.visualjava.palette.ComponentDescriptor.Category.DISPLAY

/** v1 widget set, organised by [ComponentDescriptor.Category]. */
object PaletteCatalog {

    val all: List<ComponentDescriptor> = listOf(
        // Containers
        ComponentDescriptor("Pane", "Pane", "javafx.scene.layout.Pane", CONTAINERS,
            mapOf("prefWidth" to "200", "prefHeight" to "150")),
        ComponentDescriptor("AnchorPane", "AnchorPane", "javafx.scene.layout.AnchorPane", CONTAINERS,
            mapOf("prefWidth" to "200", "prefHeight" to "150")),
        ComponentDescriptor("BorderPane", "BorderPane", "javafx.scene.layout.BorderPane", CONTAINERS,
            mapOf("prefWidth" to "300", "prefHeight" to "200")),
        ComponentDescriptor("GridPane", "GridPane", "javafx.scene.layout.GridPane", CONTAINERS,
            mapOf("prefWidth" to "300", "prefHeight" to "200", "hgap" to "8", "vgap" to "8")),
        ComponentDescriptor("StackPane", "StackPane", "javafx.scene.layout.StackPane", CONTAINERS,
            mapOf("prefWidth" to "200", "prefHeight" to "150")),
        ComponentDescriptor("HBox", "HBox", "javafx.scene.layout.HBox", CONTAINERS,
            mapOf("prefWidth" to "200", "prefHeight" to "40", "spacing" to "8")),
        ComponentDescriptor("VBox", "VBox", "javafx.scene.layout.VBox", CONTAINERS,
            mapOf("prefWidth" to "200", "prefHeight" to "150", "spacing" to "8")),
        ComponentDescriptor("FlowPane", "FlowPane", "javafx.scene.layout.FlowPane", CONTAINERS,
            mapOf("prefWidth" to "240", "prefHeight" to "120", "hgap" to "6", "vgap" to "6")),
        ComponentDescriptor("TabPane", "TabPane", "javafx.scene.control.TabPane", CONTAINERS,
            mapOf("prefWidth" to "300", "prefHeight" to "200")),
        ComponentDescriptor("ScrollPane", "ScrollPane", "javafx.scene.control.ScrollPane", CONTAINERS,
            mapOf("prefWidth" to "240", "prefHeight" to "160")),
        ComponentDescriptor("SplitPane", "SplitPane", "javafx.scene.control.SplitPane", CONTAINERS,
            mapOf("prefWidth" to "300", "prefHeight" to "200")),
        ComponentDescriptor("TitledPane", "TitledPane", "javafx.scene.control.TitledPane", CONTAINERS,
            mapOf("text" to "Title", "prefWidth" to "240", "prefHeight" to "120")),
        ComponentDescriptor("Accordion", "Accordion", "javafx.scene.control.Accordion", CONTAINERS,
            mapOf("prefWidth" to "240", "prefHeight" to "180")),
        ComponentDescriptor("ToolBar", "ToolBar", "javafx.scene.control.ToolBar", CONTAINERS,
            mapOf("prefWidth" to "400", "prefHeight" to "32")),

        // Controls
        ComponentDescriptor("Button", "Button", "javafx.scene.control.Button", CONTROLS,
            mapOf("text" to "Button", "prefWidth" to "100")),
        ComponentDescriptor("ToggleButton", "ToggleButton", "javafx.scene.control.ToggleButton", CONTROLS,
            mapOf("text" to "Toggle", "prefWidth" to "100")),
        ComponentDescriptor("MenuButton", "MenuButton", "javafx.scene.control.MenuButton", CONTROLS,
            mapOf("text" to "Menu", "prefWidth" to "100")),
        ComponentDescriptor("Label", "Label", "javafx.scene.control.Label", CONTROLS,
            mapOf("text" to "Label")),
        ComponentDescriptor("Hyperlink", "Hyperlink", "javafx.scene.control.Hyperlink", CONTROLS,
            mapOf("text" to "Link")),
        ComponentDescriptor("TextField", "TextField", "javafx.scene.control.TextField", CONTROLS,
            mapOf("prefWidth" to "200")),
        ComponentDescriptor("PasswordField", "PasswordField", "javafx.scene.control.PasswordField", CONTROLS,
            mapOf("prefWidth" to "200")),
        ComponentDescriptor("TextArea", "TextArea", "javafx.scene.control.TextArea", CONTROLS,
            mapOf("prefWidth" to "200", "prefHeight" to "100")),
        ComponentDescriptor("CheckBox", "CheckBox", "javafx.scene.control.CheckBox", CONTROLS,
            mapOf("text" to "CheckBox")),
        ComponentDescriptor("RadioButton", "RadioButton", "javafx.scene.control.RadioButton", CONTROLS,
            mapOf("text" to "RadioButton")),
        ComponentDescriptor("ComboBox", "ComboBox", "javafx.scene.control.ComboBox", CONTROLS,
            mapOf("prefWidth" to "150")),
        ComponentDescriptor("ChoiceBox", "ChoiceBox", "javafx.scene.control.ChoiceBox", CONTROLS,
            mapOf("prefWidth" to "150")),
        ComponentDescriptor("DatePicker", "DatePicker", "javafx.scene.control.DatePicker", CONTROLS,
            mapOf("prefWidth" to "150")),
        ComponentDescriptor("ColorPicker", "ColorPicker", "javafx.scene.control.ColorPicker", CONTROLS,
            mapOf("prefWidth" to "150")),
        ComponentDescriptor("Spinner", "Spinner", "javafx.scene.control.Spinner", CONTROLS,
            mapOf("prefWidth" to "100")),
        ComponentDescriptor("Slider", "Slider", "javafx.scene.control.Slider", CONTROLS,
            mapOf("prefWidth" to "200")),
        ComponentDescriptor("Separator", "Separator", "javafx.scene.control.Separator", CONTROLS,
            mapOf("prefWidth" to "200")),

        // Lists & tables
        ComponentDescriptor("ListView", "ListView", "javafx.scene.control.ListView", COLLECTIONS,
            mapOf("prefWidth" to "200", "prefHeight" to "120")),
        ComponentDescriptor("TableView", "TableView", "javafx.scene.control.TableView", COLLECTIONS,
            mapOf("prefWidth" to "300", "prefHeight" to "150")),
        ComponentDescriptor("TreeView", "TreeView", "javafx.scene.control.TreeView", COLLECTIONS,
            mapOf("prefWidth" to "200", "prefHeight" to "200")),
        ComponentDescriptor("TreeTableView", "TreeTableView", "javafx.scene.control.TreeTableView", COLLECTIONS,
            mapOf("prefWidth" to "320", "prefHeight" to "200")),
        ComponentDescriptor("MenuBar", "MenuBar", "javafx.scene.control.MenuBar", COLLECTIONS,
            mapOf("prefWidth" to "400")),

        // Display
        ComponentDescriptor("ProgressBar", "ProgressBar", "javafx.scene.control.ProgressBar", DISPLAY,
            mapOf("prefWidth" to "200", "progress" to "0.5")),
        ComponentDescriptor("ProgressIndicator", "ProgressIndicator", "javafx.scene.control.ProgressIndicator", DISPLAY,
            mapOf("prefWidth" to "40", "prefHeight" to "40", "progress" to "0.5")),
        ComponentDescriptor("ImageView", "ImageView", "javafx.scene.image.ImageView", DISPLAY,
            mapOf("fitWidth" to "100", "fitHeight" to "100", "preserveRatio" to "true")),
        ComponentDescriptor("WebView", "WebView", "javafx.scene.web.WebView", DISPLAY,
            mapOf("prefWidth" to "320", "prefHeight" to "240")),
        ComponentDescriptor("MediaView", "MediaView", "javafx.scene.media.MediaView", DISPLAY,
            mapOf("fitWidth" to "320", "fitHeight" to "180", "preserveRatio" to "true")),
        ComponentDescriptor("HTMLEditor", "HTMLEditor", "javafx.scene.web.HTMLEditor", DISPLAY,
            mapOf("prefWidth" to "400", "prefHeight" to "200")),
        ComponentDescriptor("LineChart", "LineChart", "javafx.scene.chart.LineChart", DISPLAY,
            mapOf("prefWidth" to "400", "prefHeight" to "240"),
            bodyXml = "<xAxis><NumberAxis/></xAxis><yAxis><NumberAxis/></yAxis>",
            extraImports = listOf("javafx.scene.chart.NumberAxis")),
        ComponentDescriptor("BarChart", "BarChart", "javafx.scene.chart.BarChart", DISPLAY,
            mapOf("prefWidth" to "400", "prefHeight" to "240"),
            bodyXml = "<xAxis><CategoryAxis/></xAxis><yAxis><NumberAxis/></yAxis>",
            extraImports = listOf("javafx.scene.chart.CategoryAxis", "javafx.scene.chart.NumberAxis")),
        ComponentDescriptor("PieChart", "PieChart", "javafx.scene.chart.PieChart", DISPLAY,
            mapOf("prefWidth" to "320", "prefHeight" to "240")),
        ComponentDescriptor("AreaChart", "AreaChart", "javafx.scene.chart.AreaChart", DISPLAY,
            mapOf("prefWidth" to "400", "prefHeight" to "240"),
            bodyXml = "<xAxis><NumberAxis/></xAxis><yAxis><NumberAxis/></yAxis>",
            extraImports = listOf("javafx.scene.chart.NumberAxis")),
        ComponentDescriptor("ScatterChart", "ScatterChart", "javafx.scene.chart.ScatterChart", DISPLAY,
            mapOf("prefWidth" to "400", "prefHeight" to "240"),
            bodyXml = "<xAxis><NumberAxis/></xAxis><yAxis><NumberAxis/></yAxis>",
            extraImports = listOf("javafx.scene.chart.NumberAxis")),
    )

    fun byTag(tag: String): ComponentDescriptor? = all.firstOrNull { it.tagName == tag }
}
